import turtle
import time
point=turtle.Turtle()
point.color('gray')
point.width(3)
point.hideturtle()
time.sleep(1)

point.penup()
point.setposition(-30,60)
point.pendown()
point.forward(60)
point.right(90)   
point.forward(120)
point.right(90)     
point.forward(60)
point.right(90) 
point.forward(120)
time.sleep(1)

red=turtle.Turtle()
red.shape('circle')
red.color('gray')
red.penup()
red.setposition(0,40)
#time.sleep(1)

yellow=turtle.Turtle()
yellow.shape('circle')
yellow.color('gray')
yellow.penup()
yellow.setposition(0,0)

green=turtle.Turtle()
green.shape('circle')
green.color('gray')
green.penup()
green.setposition(0,-40)
time.sleep(1)


yellow.color('yellow')
time.sleep(1)
yellow.color('gray')
time.sleep(1)
yellow.color('yellow')
time.sleep(1)
yellow.color('gray')
time.sleep(1)
yellow.color('yellow')
time.sleep(1)
yellow.color('gray')
while True:
 red.color('red')
 time.sleep(4)
 red.color('gray')
 yellow.color('yellow')
 time.sleep(3)
 yellow.color('gray')
 green.color('green')
 time.sleep(4)

 green.color('green')
 time.sleep(1)
 green.color('gray')
 time.sleep(1)
 green.color('green')
 time.sleep(1)
 green.color('gray')
 time.sleep(1)
 green.color('green')
 time.sleep(1)
 green.color('gray')
 time.sleep(1)
 green.color('green')
 time.sleep(1)
 green.color('gray')

 yellow.color('yellow')
 time.sleep(3)
 yellow.color('gray')
 red.color('red')
 time.sleep(1)

